version: "3.8"

services:
  consul:
    image: hashicorp/consul:1.15.4
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  quiz:
    build:
      context: ./quiz
    env_file:
      - ./quiz/.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - consul
      - rabbitmq

  question:
    build:
      context: ./question
    env_file:
      - ./question/.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - consul
      - rabbitmq

  result:
    build:
      context: ./result
    env_file:
      - ./result/.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - consul
      - rabbitmq

  ai:
    build:
      context: ./ai
    env_file:
      - ./ai/.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - consul
      - rabbitmq

  gateway:
    build:
      context: ./gateway
    env_file:
      - ./gateway/.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - consul
      - quiz
      - question
      - result
      - ai

  app:
    build:
      context: ./app
    ports:
      - "3000:80"
    depends_on:
      - gateway

  mysql-quiz:
    image: mysql:8.0
    env_file:
      - ./quiz/.env
    environment:
      MYSQL_DATABASE: quizdb
    ports:
      - "3306"

  mysql-question:
    image: mysql:8.0
    env_file:
      - ./question/.env
    environment:
      MYSQL_DATABASE: questiondb
    ports:
      - "3307"

  mysql-result:
    image: mysql:8.0
    env_file:
      - ./result/.env
    environment:
      MYSQL_DATABASE: resultdb
    ports:
      - "3308"

volumes:
  quiz-data:
  question-data:
  result-data:
